# Functions/models for computing nullclines of equations defined in Martinez2012
# to model germinal cell center regulation

using PlasmaCellDiff
using UnPack

"""
    blimp1_nullcline(bcl6_level, params::GerminalCenterODEParams)  

```math
\\begin{equation}
\\dot{p} = 0 \\Leftrightarrow n_p(b) = p = \\frac{\\mu_p + \\sigma_p \\frac{k_b^2}{k_b^2 + b^2}}{\\lambda_p}
\\end{equation}
```

Return nullcline for BLIMP1 (`p`).

# References
[1] : Equation S6 from Martinez2012

[2] : https://www.normalesup.org/~doulcier/teaching/modeling/bistable_systems.html
"""
function blimp1_nullcline(bcl6_level, params::GerminalCenterODEParams)
    # parameters 
    @unpack μp, σp, λp, kb = params

    # transcription factor state variables 
    b = bcl6_level

    kb_scaled = dissociation_scaler(kb, b)
    p_nullcline = (μp + σp*kb_scaled)/λp
 
    return p_nullcline
end 

"""
    bcl6_nullcline(bcl6_level, params::GerminalCenterODEParams) 

```math
TODO:
\\begin{equation}
\\dot{x} = y
\\end{equation}
```

Return nullcline for BCL6 (`b`). Solution generated by mathematica.

NOTE: After discussion with Dr. A. van Kampen, it seems numerically
computing the nullclines is the best choice. The package options are 
phaseR (in CRAN) or homerolled grind.R (university utrecht)

NOTE: Since the solution works out to be `p^2 = RHS`, then the solution should 
be `p = +-sqrt(RHS)`, but since negative protein levels are not physically 
interpretable, only +b_nullcline is returned.

# References
[1] : Equation S7 from Martinez2012

[2] : https://www.normalesup.org/~doulcier/teaching/modeling/bistable_systems.html
"""
function bcl6_nullcline(bcl6_level, params::GerminalCenterODEParams)
    # parameters 
    @unpack kp, kb, σb, μb, λb, bcr_constant = params

    b = bcl6_level
 
    # hand solved 
    b_nullcline = sqrt((kp^2*σb*kb^2)/
        ((b*λb + b*bcr_constant - μb)*(kb^2 + b^2)) - kp^2)
    
    # mathematica solved
    #numer = kp*√( (b^2 + kb^2)*(b*(bcr_constant + λb) - μb) - kb^2*σb )
    #denom = √( -((b^2 + kb^2)*(b*(bcr_constant + λb) - μb)) ) 
    #b_nullcline = numer / denom
    
    return b_nullcline
end 
